name = "cuestionarios-ldsm"
compatibility_date = "2026-07-15"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "ldsm-cuestionarios"
database_id = "45168d93-d02e-43fd-9836-b522667f24f6"

[vars]
TURNSTILE_SITE_KEY = ""
