name = "cuestionarios-ldsm"
compatibility_date = "2026-07-15"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "ldsm-cuestionarios"
database_id = "00000000-0000-0000-0000-000000000000"

[vars]
PUBLIC_BASE_URL = "http://localhost:8788"
TURNSTILE_SITE_KEY = ""
