-- Bandeja diaria, cierre operacional, ficha familiar y catálogos administrables.

CREATE TABLE IF NOT EXISTS eventos_operacionales (
  id BIGSERIAL PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL
    CHECK (tipo IN (
      'INGRESO_DUPLICADO', 'CODIGO_NO_ENCONTRADO', 'IMPORTACION_RECHAZADA',
      'VISITA_ABIERTA', 'RETIRO_PENDIENTE', 'OTRO'
    )),
  estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
    CHECK (estado IN ('PENDIENTE', 'RESUELTO', 'DESCARTADO')),
  entidad VARCHAR(60),
  entidad_id BIGINT,
  detalle JSONB NOT NULL DEFAULT '{}'::jsonb,
  ocurrido_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  registrado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  resuelto_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  resuelto_en TIMESTAMPTZ,
  motivo_resolucion VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_eventos_operacionales_pendientes
  ON eventos_operacionales (estado, ocurrido_en DESC);

CREATE TABLE IF NOT EXISTS cierres_operacionales (
  id BIGSERIAL PRIMARY KEY,
  fecha DATE NOT NULL UNIQUE,
  resumen JSONB NOT NULL,
  observaciones VARCHAR(1000),
  cerrado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  cerrado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_cierres_operacionales_fecha
  ON cierres_operacionales (fecha DESC);

ALTER TABLE visitantes
  ADD COLUMN IF NOT EXISTS telefono_emergencia VARCHAR(40),
  ADD COLUMN IF NOT EXISTS restricciones VARCHAR(1000),
  ADD COLUMN IF NOT EXISTS observaciones_familiares VARCHAR(1000);

ALTER TABLE personas_autorizadas_retiro
  ADD COLUMN IF NOT EXISTS tipo_responsabilidad VARCHAR(30) NOT NULL DEFAULT 'AUTORIZADO',
  ADD COLUMN IF NOT EXISTS telefono_emergencia VARCHAR(40),
  ADD COLUMN IF NOT EXISTS restricciones VARCHAR(1000),
  ADD COLUMN IF NOT EXISTS observaciones VARCHAR(1000);

ALTER TABLE personas_autorizadas_retiro
  DROP CONSTRAINT IF EXISTS ck_autorizacion_tipo_responsabilidad;

ALTER TABLE personas_autorizadas_retiro
  ADD CONSTRAINT ck_autorizacion_tipo_responsabilidad
  CHECK (tipo_responsabilidad IN ('PRINCIPAL', 'SUPLENTE', 'AUTORIZADO'));

UPDATE personas_autorizadas_retiro
SET tipo_responsabilidad = CASE
  WHEN es_principal THEN 'PRINCIPAL'
  WHEN parentesco_codigo = 'APODERADO_SUPLENTE' THEN 'SUPLENTE'
  ELSE 'AUTORIZADO'
END;

CREATE TABLE IF NOT EXISTS autorizacion_retiro_eventos (
  id BIGSERIAL PRIMARY KEY,
  autorizacion_id BIGINT NOT NULL REFERENCES personas_autorizadas_retiro(id) ON DELETE RESTRICT,
  accion VARCHAR(30) NOT NULL
    CHECK (accion IN ('CREAR', 'ACTUALIZAR', 'DESACTIVAR', 'REACTIVAR', 'IMPORTAR')),
  antes JSONB,
  despues JSONB,
  motivo VARCHAR(500) NOT NULL,
  realizado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  realizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_autorizacion_eventos
  ON autorizacion_retiro_eventos (autorizacion_id, realizado_en DESC);

ALTER TABLE visita_motivos
  ADD COLUMN IF NOT EXISTS requiere_detalle BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS actualizado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE visita_destinos
  ADD COLUMN IF NOT EXISTS requiere_contacto BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS actualizado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE retiro_motivos
  ADD COLUMN IF NOT EXISTS actualizado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tipos_parentesco
  ADD COLUMN IF NOT EXISTS actualizado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE visita_motivos SET requiere_detalle = true WHERE codigo = 'OTRO';
UPDATE visita_destinos SET requiere_contacto = true WHERE codigo IN ('DIRECCION', 'INSPECTORIA', 'UTP', 'CONVIVENCIA', 'OTRO');

CREATE TABLE IF NOT EXISTS configuracion_visitas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hora_cierre TIME NOT NULL DEFAULT '18:00:00',
  max_horas_visita INT NOT NULL DEFAULT 8 CHECK (max_horas_visita BETWEEN 1 AND 24),
  exigir_documento_fisico BOOLEAN NOT NULL DEFAULT true,
  permitir_retiro_excepcional BOOLEAN NOT NULL DEFAULT true,
  actualizado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_configuracion_visitas_singleton
  ON configuracion_visitas ((true));

INSERT INTO configuracion_visitas (
  hora_cierre, max_horas_visita, exigir_documento_fisico, permitir_retiro_excepcional
)
SELECT '18:00:00', 8, true, true
WHERE NOT EXISTS (SELECT 1 FROM configuracion_visitas);

CREATE TABLE IF NOT EXISTS politicas_retencion (
  categoria VARCHAR(40) PRIMARY KEY
    CHECK (categoria IN ('RUT_TELEFONOS', 'AUDITORIA', 'DOCUMENTOS', 'VISITAS_RETIROS')),
  dias_retencion INT CHECK (dias_retencion IS NULL OR dias_retencion BETWEEN 30 AND 3650),
  modo VARCHAR(30) NOT NULL DEFAULT 'SOLO_PREVISUALIZAR'
    CHECK (modo IN ('SOLO_PREVISUALIZAR', 'APROBADA_SIN_EJECUTAR')),
  fundamento VARCHAR(1000),
  actualizado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO politicas_retencion (categoria, dias_retencion, fundamento) VALUES
  ('RUT_TELEFONOS', NULL, 'Pendiente de aprobación institucional'),
  ('AUDITORIA', NULL, 'Pendiente de aprobación institucional'),
  ('DOCUMENTOS', NULL, 'Pendiente de aprobación institucional'),
  ('VISITAS_RETIROS', NULL, 'Pendiente de aprobación institucional')
ON CONFLICT (categoria) DO NOTHING;

INSERT INTO permisos_sistema (codigo, grupo, etiqueta, descripcion, orden, critico) VALUES
  ('operations.view', 'Operación diaria', 'Ver tareas por resolver', 'Consulta pendientes operativos, respaldo y estado del servicio.', 235, false),
  ('operations.close', 'Operación diaria', 'Cerrar jornada operacional', 'Cierra exclusivamente visitas y retiros una vez resueltos los pendientes.', 236, true),
  ('family.manage', 'Visitas y retiros', 'Administrar ficha familiar', 'Mantiene responsables, vínculos, vigencias y restricciones con historial.', 237, true)
ON CONFLICT (codigo) DO UPDATE SET
  grupo = EXCLUDED.grupo,
  etiqueta = EXCLUDED.etiqueta,
  descripcion = EXCLUDED.descripcion,
  orden = EXCLUDED.orden,
  critico = EXCLUDED.critico;

INSERT INTO permisos_rol (rol, permiso_codigo) VALUES
  ('admin', 'operations.view'),
  ('admin', 'operations.close'),
  ('admin', 'family.manage'),
  ('inspector', 'operations.view'),
  ('inspector', 'operations.close'),
  ('inspector', 'family.manage'),
  ('secretaria', 'operations.view'),
  ('secretaria', 'family.manage'),
  ('direccion', 'operations.view')
ON CONFLICT DO NOTHING;
